name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  check-cs:
    name: Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          # Keep in sync with PHP version pinned in tools/php-cs-fixer/composer.json
          php-version: '8.3'

      - name: Install PHP CS Fixer dependencies
        uses: ramsey/composer-install@v2
        with:
          working-directory: tools/php-cs-fixer

      - name: Run PHP CS Fixer
        run: tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php

  phpstan:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          # Keep in sync with PHP version pinned in tools/phpstan/composer.json
          php-version: '8.3'

      - name: Install PHPStan dependencies
        uses: ramsey/composer-install@v2
        with:
          working-directory: tools/phpstan

      - name: Install Castor dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: --prefer-dist --no-progress --optimize-autoloader --classmap-authoritative

      - name: Run PHPStan
        run: tools/phpstan/vendor/bin/phpstan --configuration=phpstan.neon

  phpunit:
    name: PHPUnit on ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ "8.1", "8.2", "8.3" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install Castor dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: --prefer-dist --no-progress --optimize-autoloader --classmap-authoritative

      - name: Install dependencies (phar builder)
        uses: ramsey/composer-install@v2
        with:
          working-directory: tools/phar

      - name: Link box
        run: sudo ln -s $GITHUB_WORKSPACE/tools/phar/vendor/bin/box /usr/local/bin/box

      - name: Install PHPUnit
        run: vendor/bin/simple-phpunit install

      - name: Run tests
        run: vendor/bin/simple-phpunit
