name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  check-cs:
    name: Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PHP-CS-Fixer
        uses: docker://ghcr.io/php-cs-fixer/php-cs-fixer:3-php8.3
        with:
          args: --config=.php-cs-fixer.php check --diff

  phpstan:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        env:
          REQUIRE_DEV: true

  phpunit:
    name: "PHPUnit on ${{ matrix.php }} ${{ matrix.phar && '(with phar)' || '' }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ "8.1", "8.2", "8.3" ]
        phar: [ false ]
        include:
          - php: "8.1"
            phar: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"

      - name: Install dependencies (project)
        run: composer install --prefer-dist --no-progress --optimize-autoloader --classmap-authoritative

      # Needed because we repack an application in some tests
      - name: Install dependencies (phar builder)
        run: composer install --prefer-dist --no-progress --optimize-autoloader --classmap-authoritative
        working-directory: tools/phar

      - name: Compile phar Linux
        run: bin/castor castor:phar:linux
        shell: bash
        if: matrix.phar

      - name: Link box
        run: sudo ln -s $GITHUB_WORKSPACE/tools/phar/vendor/bin/box /usr/local/bin/box

      - name: Install PHPUnit
        run: vendor/bin/simple-phpunit install

      - name: Run tests
        run: vendor/bin/simple-phpunit
        env:
          CASTOR_BIN: ${{ github.workspace }}/${{ matrix.phar && 'tools/phar/build/castor.linux-amd64.phar' || 'bin/castor'}}

  phar:
    name: Ensure PHAR is OK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build all the phars
        uses: ./.github/actions/phar
