name: Attach phars to the release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  phar_release:
    name: Create phars and upload them
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build all the phars
        uses: ./.github/actions/phar

      - name: Upload files
        run: |
          gh release upload ${{ github.ref_name }} ./tools/phar/build/castor.linux-amd64.phar
          gh release upload ${{ github.ref_name }} ./tools/phar/build/castor.darwin-amd64.phar
          gh release upload ${{ github.ref_name }} ./tools/phar/build/castor.windows-amd64.phar
        env:
          GH_TOKEN: ${{ github.token }}
